# Generated by Django 6.0.7 on 2026-08-23 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBonusPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(verbose_name='Название')),
                ('internal_value', models.CharField(verbose_name='Содержимое')),
                ('weight', models.PositiveBigIntegerField(default=10, verbose_name='Шанс выпадения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('points', models.IntegerField(default=10, verbose_name='Очки')),
            ],
            options={
                'verbose_name': 'Ежедневный бонус',
                'verbose_name_plural': 'Ежедневные бонусы',
            },
        ),
        migrations.CreateModel(
            name='WheelPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(verbose_name='Название')),
                ('internal_value', models.CharField(verbose_name='Содержимое')),
                ('weight', models.PositiveBigIntegerField(default=10, verbose_name='Шанс выпадения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('points', models.IntegerField(default=100, verbose_name='Очки')),
            ],
            options={
                'verbose_name': 'Приз на колесе',
                'verbose_name_plural': 'Призы на колесе',
                'ordering': ('-weight',),
            },
        ),
        migrations.CreateModel(
            name='DailyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Промокод')),
                ('is_redeemed', models.BooleanField(default=False, verbose_name='Использован')),
                ('got_at', models.DateTimeField(auto_now_add=True, verbose_name='Получен')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('use_after', models.DateTimeField(blank=True, null=True, verbose_name='Использовать после')),
                ('use_until', models.DateTimeField(blank=True, null=True, verbose_name='Просрочится')),
                ('is_expired', models.BooleanField(default=False, verbose_name='Просрочен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('prize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_bonuses', to='wheel.dailybonusprize', verbose_name='Выигрыш')),
            ],
            options={
                'verbose_name': 'Бонус пользователя',
                'verbose_name_plural': 'Бонусы пользователя',
                'ordering': ('-got_at',),
            },
        ),
        migrations.CreateModel(
            name='PromocodePrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(verbose_name='Название')),
                ('internal_value', models.CharField(verbose_name='Содержимое')),
                ('promo_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Промокод')),
                ('is_redeemed', models.BooleanField(default=False, verbose_name='Получен')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('got_at', models.DateTimeField(auto_now_add=True, verbose_name='Получен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ('-got_at',),
            },
        ),
        migrations.CreateModel(
            name='Spin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Промокод')),
                ('is_redeemed', models.BooleanField(default=False, verbose_name='Получен')),
                ('spun_at', models.DateTimeField(auto_now_add=True, verbose_name='Прокручен')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('prize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winnig_spins', to='wheel.wheelprize', verbose_name='Выигрыш')),
            ],
            options={
                'verbose_name': 'Спин пользователя',
                'verbose_name_plural': 'Спины пользователя',
                'ordering': ('-spun_at',),
            },
        ),
    ]
