# Generated by Django 6.0.7 on 2026-09-09 23:35

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubUser',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('mobile_phone', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Номер телефона')),
                ('age', models.PositiveSmallIntegerField(default=1, verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Клубный пользователь',
                'verbose_name_plural': 'Клубные пользователи',
                'ordering': ('mobile_phone',),
            },
        ),
        migrations.CreateModel(
            name='MonthlyLadderArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=50, verbose_name='Название месяца')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('month', models.PositiveIntegerField(verbose_name='Номер месяца')),
                ('total_players', models.PositiveIntegerField(default=0, verbose_name='Всего участников')),
                ('total_points', models.BigIntegerField(default=0, verbose_name='Общая сумма очков')),
                ('top_players', models.JSONField(default=list, verbose_name='Топ 10 игроков')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата архивации')),
            ],
            options={
                'verbose_name': 'Архив ладдера',
                'verbose_name_plural': 'Архивы ладдеров',
                'ordering': ('-year', '-month'),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Логин')),
                ('telegram_id', models.CharField(unique=True, verbose_name='Телеграм ID')),
                ('monthly_points', models.IntegerField(default=0, verbose_name='Очки')),
                ('available_spins', models.IntegerField(default=1, verbose_name='Спины')),
                ('last_spin', models.DateTimeField(blank=True, null=True, verbose_name='Последний спин')),
                ('total_spins', models.IntegerField(default=0, verbose_name='Всего спинов')),
                ('daily_streak', models.IntegerField(default=0, verbose_name='Ежедневный стрик')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('mobile_phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_user_phones', to='users.clubuser', verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('username',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClubTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_rub', models.PositiveIntegerField(verbose_name='Сумма чека')),
                ('check_number', models.CharField(max_length=200, unique=True, verbose_name='Номер чека ФД')),
                ('spins_awarded', models.PositiveIntegerField(blank=True, verbose_name='Полученные спины')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Админ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
